apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-v2
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: Force=true,Replace=true
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
